server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board?serverTimezone=Asia/Seoul
    username: developer
    password: ${SPRING_DATASOURCE_PASSWORD}

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 110MB

--- 

## for OAuth2.0 Authorization

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 879009587236-66msuokgvhmlcf5g0d9hbd2hsqe4qbdo.apps.googleusercontent.com
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: http://localhost:8080/oauth2/callback/google
            scope: 
              - profile
              - email

          naver:
            client-id: 7jTV7H2xxTRrPMx1KbCG
            client-secret: ${NAVER_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/oauth2/callback/naver
            scope: 
              - name
              - email
              - profile_image
            client-name: Naver

          kakao:
            client-id: 7cc82c16012d37571222e151afb6d966
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            redirect-uri: http://localhost:8080/oauth2/callback/kakao
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정

secret-key: ${SECRET_KEY}

file:
  path: D:/fileUpload/ 
  url: http://localhost:8080/file/

logging:
  level:
    org:
      springframework:
        web: INFO


